# Generated by Django 3.1.6 on 2021-08-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('topico', models.CharField(max_length=200)),
                ('cantidad_de_preguntas', models.IntegerField(max_length=200)),
                ('tiempo', models.IntegerField(help_text='Duracion del quiz en minutos')),
                ('dificultad', models.CharField(choices=[('facil', 'facil'), ('intermedio', 'intermedio'), ('dificil', 'dificil')], max_length=10)),
            ],
        ),
    ]
