# Generated by Django 3.1 on 2021-08-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=50)),
                ('topico', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_maximo', models.IntegerField(null=True)),
                ('puntaje_juego', models.IntegerField(null=True)),
                ('dificultad', models.CharField(default='normal', max_length=20)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=200)),
                ('opcion_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
                ('id_partida', models.ForeignKey(blank=True, db_column='id_partida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('id_respuesta', models.ForeignKey(blank=True, db_column='id_respuesta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.respuesta')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_pregunta',
            field=models.ForeignKey(blank=True, db_column='id_pregunta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.pregunta'),
        ),
    ]
