# Generated by Django 3.1.6 on 2021-08-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_categoria_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida', models.IntegerField()),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id_pregunta',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='dificultad',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='correcto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='incorrecto_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='incorrecto_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='incorrecto_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='incorrecto_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='pregunta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='victoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='puntaje_juego',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='puntaje_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='partida',
            name='id_date',
            field=models.ForeignKey(blank=True, db_column='id_date', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.date'),
        ),
        migrations.AddField(
            model_name='partida',
            name='id_dificultad',
            field=models.ForeignKey(blank=True, db_column='id_dificultad', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.dificultad'),
        ),
    ]
