# Generated by Django 3.1.6 on 2021-08-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210824_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.usuario'),
        ),
    ]
