# Generated by Django 3.1.6 on 2021-08-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210826_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_quiz',
            field=models.ForeignKey(blank=True, db_column='id_quiz', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='categorias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
