# Generated by Django 3.1.6 on 2021-08-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210826_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='categorias',
            new_name='categoria_preg',
        ),
    ]
