# Generated by Django 3.1.6 on 2021-08-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210824_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
    ]
