# Generated by Django 3.1.6 on 2021-08-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210826_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='correcto',
            new_name='respuesta_1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='incorrecto_1',
            new_name='respuesta_2',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='incorrecto_2',
            new_name='respuesta_3',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='incorrecto_3',
            new_name='respuesta_4',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='incorrecto_4',
            new_name='respuesta_5',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcta',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
