# Generated by Django 3.1.6 on 2021-08-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210825_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='id_respuesta',
            field=models.ForeignKey(blank=True, db_column='id_respuesta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.respuesta'),
        ),
    ]
