# Generated by Django 3.1.6 on 2021-08-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_quiz_categoria_preg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correcta',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcto_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcto_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcto_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcto_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correcto_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.categoria'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pregunta',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
