# Generated by Django 3.1.6 on 2021-08-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210828_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
