# Generated by Django 3.1.6 on 2021-08-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210825_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_maximo', models.IntegerField(null=True)),
                ('puntaje_juego', models.IntegerField(null=True)),
                ('dificultad', models.CharField(default='normal', max_length=20)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.categoria')),
            ],
        ),
    ]
