# Generated by Django 3.1.6 on 2021-08-26 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_partida',
            field=models.ForeignKey(blank=True, db_column='id_partida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.partida'),
        ),
    ]
