# Generated by Django 3.1.6 on 2021-08-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=250, null=True)),
                ('respuesta_1', models.CharField(blank=True, max_length=200, null=True)),
                ('correcto_1', models.BooleanField(default=False)),
                ('respuesta_2', models.CharField(blank=True, max_length=200, null=True)),
                ('correcto_2', models.BooleanField(default=False)),
                ('respuesta_3', models.CharField(blank=True, max_length=200, null=True)),
                ('correcto_3', models.BooleanField(default=False)),
                ('respuesta_4', models.CharField(blank=True, max_length=200, null=True)),
                ('correcto_4', models.BooleanField(default=False)),
                ('respuesta_5', models.CharField(blank=True, max_length=200, null=True)),
                ('correcto_5', models.BooleanField(default=False)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.categoria')),
            ],
        ),
    ]
