# Generated by Django 3.1.6 on 2021-08-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210828_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.CharField(blank=True, max_length=20, null=True)),
                ('vida', models.IntegerField(blank=True, null=True)),
                ('tiempo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='id_dificultad',
            field=models.ForeignKey(blank=True, db_column='id_dificultad', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.dificultad'),
        ),
    ]
