# Generated by Django 3.1.6 on 2021-08-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_dificultad_cant_preguntas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dificultad',
            old_name='cant_preguntas',
            new_name='cant_respuestas',
        ),
    ]
