# Generated by Django 3.1 on 2021-09-03 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_auto_20210829_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='personaje',
            field=models.CharField(default='gaucho', max_length=50),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
