# Generated by Django 3.1.6 on 2021-09-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20210903_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_maximo', models.IntegerField(blank=True, null=True)),
                ('puntaje_juego', models.IntegerField(blank=True, null=True)),
                ('personaje', models.CharField(default='gaucho', max_length=50)),
                ('id_dificultad', models.ForeignKey(blank=True, db_column='id_dificultad', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.dificultad')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.usuario')),
            ],
        ),
    ]
