# Generated by Django 3.1.6 on 2021-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='personaje',
            field=models.CharField(blank=True, default='gaucho', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='victoria',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
