# Generated by Django 3.1.6 on 2021-09-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20210903_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
