# Generated by Django 3.1.6 on 2021-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_delete_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='id_date',
        ),
        migrations.AddField(
            model_name='partida',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
