# Generated by Django 3.1.6 on 2021-09-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20210903_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
