# Generated by Django 3.1 on 2021-09-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20210903_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
