# Generated by Django 3.1 on 2021-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_rankingusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingusuario',
            name='puntaje_maximo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
