# Generated by Django 3.1 on 2021-09-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20210907_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankingUsuario',
        ),
    ]
