# Generated by Django 3.1 on 2021-12-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_maximo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
